# letsencrypt-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer # Use ClusterIssuer to issue certs in any namespace
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Email address used for ACME registration
    email: administrative@loyalshift.com # <-- CHANGE THIS to your email
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-prod-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx # Matches your ingressClassName
