server {
  listen 80;
  server_name _; # Listen on any hostname

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    # Try to serve the requested file directly, then as a directory,
    # otherwise redirect to index.html (for SPA route handling)
    try_files $uri $uri/ /index.html;
  }

  # Additional Nginx configuration if needed (e.g., cache, gzip)
  # gzip on;
  # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
